# Generated by Django 5.0.1 on 2024-01-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('precio_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_cierre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen', models.IntegerField()),
            ],
        ),
    ]
